### ISSUE TITLE
Guru Meditation Error when using library in C++ environment

### ISSUE THREAD

**Issue by aronfeher** [Andrey-m/MQTT-lib-for-esp-idf#1]
First of all, This is an amazing library. 
I've been using it for a while in C environment without any problems.

Recently I've been trying to incorporate it into C++ (the same code, that was working before), and I've got some nasty exceptions:

_Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x400014e8  PS      : 0x00060530  A0      : 0x80001459  A1      : 0x3ffcc590
A2      : 0x0000000e  A3      : 0x0000000c  A4      : 0x000000ff  A5      : 0x0000ff00
A6      : 0x00ff0000  A7      : 0xff000000  A8      : 0x8008b926  A9      : 0x3ffcc560
A10     : 0x3ffcc72c  A11     : 0x00001800  A12     : 0x00000000  A13     : 0x00000000
A14     : 0x00000000  A15     : 0x3ffaff50  SAR     : 0x00000004  EXCCAUSE: 0x0000001c
EXCVADDR: 0x0000000c  LBEG    : 0x4000c46c  LEND    : 0x4000c477  LCOUNT  : 0x00000000

Backtrace: 0x400014e8:0x3ffcc590 0x40001456:0x3ffcc5a0 0x40001445:0x3ffcc5c0 0x400d29de:0x3ffcc5e0 0x400d2078:0x3ffcc620 0x400d4d78:0x3ffcc6a0_

So far I've been searching for the cause, but I didn't find any solutions. 
The main.cpp can be seen below:

`#include "system.h"
//#include "peripheral.h"
#include "main_header.h"

static esp_err_t wifi_event_handler(void *ctx, system_event_t *event)
{
    switch (event->event_id) {
        case SYSTEM_EVENT_STA_START:
            esp_wifi_connect();
            break;
        case SYSTEM_EVENT_STA_GOT_IP:
            xEventGroupSetBits(wifi_event_group, CONNECTED_BIT);

            break;
        case SYSTEM_EVENT_STA_DISCONNECTED:
            esp_wifi_connect();
            xEventGroupClearBits(wifi_event_group, CONNECTED_BIT);
            break;
        default:
            break;
    }
    return ESP_OK;
}

static void wifi_init(void)
{
    tcpip_adapter_init();
    wifi_event_group = xEventGroupCreate();
    ESP_ERROR_CHECK(esp_event_loop_init(wifi_event_handler, NULL));
    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
    ESP_ERROR_CHECK(esp_wifi_init(&cfg));
    ESP_ERROR_CHECK(esp_wifi_set_storage(WIFI_STORAGE_RAM));

    wifi_config_t wifi_config;
    memset(&wifi_config, 0, sizeof(wifi_config));
	memcpy(wifi_config.sta.ssid, CONFIG_WIFI_SSID, sizeof(CONFIG_WIFI_SSID));
	memcpy(wifi_config.sta.password, CONFIG_WIFI_PASSWORD, sizeof(CONFIG_WIFI_PASSWORD));
    wifi_config.sta.bssid_set = 0;

    ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_STA));
    ESP_ERROR_CHECK(esp_wifi_set_config(ESP_IF_WIFI_STA, &wifi_config));
    ESP_LOGI(TAG, "start the WIFI SSID:[%s]", CONFIG_WIFI_SSID);
    ESP_ERROR_CHECK(esp_wifi_start());
    ESP_LOGI(TAG, "Waiting for wifi");
    xEventGroupWaitBits(wifi_event_group, CONNECTED_BIT, false, true, portMAX_DELAY);
}

static esp_err_t mqtt_event_handler(esp_mqtt_event_handle_t event)
{
    esp_mqtt_client_handle_t client = event->client;
    int msg_id;
    // your_context_t *context = event->context;
    switch (event->event_id) {
        case MQTT_EVENT_CONNECTED:
            ESP_LOGI(TAG, "MQTT_EVENT_CONNECTED");
            msg_id = esp_mqtt_client_publish(client, "/topic/qos1", "data_3", 0, 1, 0);
            ESP_LOGI(TAG, "sent publish successful, msg_id=%d", msg_id);

            msg_id = esp_mqtt_client_subscribe(client, "/topic/qos0", 0);
            ESP_LOGI(TAG, "sent subscribe successful, msg_id=%d", msg_id);

            msg_id = esp_mqtt_client_subscribe(client, "/topic/qos1", 1);
            ESP_LOGI(TAG, "sent subscribe successful, msg_id=%d", msg_id);

            msg_id = esp_mqtt_client_unsubscribe(client, "/topic/qos1");
            ESP_LOGI(TAG, "sent unsubscribe successful, msg_id=%d", msg_id);
            break;
        case MQTT_EVENT_DISCONNECTED:
            ESP_LOGI(TAG, "MQTT_EVENT_DISCONNECTED");
            break;

        case MQTT_EVENT_SUBSCRIBED:
            ESP_LOGI(TAG, "MQTT_EVENT_SUBSCRIBED, msg_id=%d", event->msg_id);
            msg_id = esp_mqtt_client_publish(client, "/topic/qos0", "data", 0, 0, 0);
            ESP_LOGI(TAG, "sent publish successful, msg_id=%d", msg_id);
            break;
        case MQTT_EVENT_UNSUBSCRIBED:
            ESP_LOGI(TAG, "MQTT_EVENT_UNSUBSCRIBED, msg_id=%d", event->msg_id);
            break;
        case MQTT_EVENT_PUBLISHED:
            ESP_LOGI(TAG, "MQTT_EVENT_PUBLISHED, msg_id=%d", event->msg_id);
            break;
        case MQTT_EVENT_DATA:
            ESP_LOGI(TAG, "MQTT_EVENT_DATA");
            printf("TOPIC=%.*s\r\n", event->topic_len, event->topic);
            printf("DATA=%.*s\r\n", event->data_len, event->data);

            
            //strcpy(str, event->data);

            //num = atoi(str);
            

            break;
        case MQTT_EVENT_ERROR:
            ESP_LOGI(TAG, "MQTT_EVENT_ERROR");
            break;
        default:
            ESP_LOGI(TAG, "Other event id:%d", event->event_id);
            break;
    }
    return ESP_OK;
}

static void mqtt_app_start(void)
{

    esp_mqtt_client_config_t mqtt_cfg;
    mqtt_cfg.uri = CONFIG_BROKER_URL;
    mqtt_cfg.event_handle = mqtt_event_handler;

    esp_mqtt_client_handle_t client = esp_mqtt_client_init(&mqtt_cfg);
    esp_mqtt_client_start(client);
}

extern "C" void app_main(){

     //initialize non-volatile flash storage media.
    esp_err_t ret = nvs_flash_init();
    if (ret == ESP_ERR_NVS_NO_FREE_PAGES) {
        ESP_ERROR_CHECK(nvs_flash_erase());
        ret = nvs_flash_init();
    }

     ESP_ERROR_CHECK( ret );

    // Initialize the left and right motor pwm signal with 25kHz 12b res.
 //   PWM motorPWM = PWM(PWM_FREQ, PWM_RES, PWM_PIN_1, PWM_PIN_2);

    wifi_init();
    // Initialize the MQTT client
    mqtt_app_start();
    

    // while(1){
    //      vTaskDelay(1000/portTICK_PERIOD_MS); 
    // }
}`

I've been debugging the project with a minimodule, and so far the wifi_init() is okay, the mqtt_app_start() runs, and in the event_handler the publish function is called - the message is sent to node-red successfully. And then the PC goes into a trap, and restarts everything.

Now I can't figure it out if I did something really nasty here, and can't see it, or the library has some c++ incompatibilities, or it's simply something else.

**Comment by Andrey-m** [comment]
Sorry, but the library is not compatible with C++

**Comment by aronfeher** [comment]
Oh... So I missed that detail somewhere in the lines.  
Then I guess I have to convert some files.
Thank you for the fast reply.
